<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof RouteNotFoundException) {
            return response()->json([
                'code' => 403,
                'message' => 'Ограничено в доступе'
            ], 403);
        }
        if ($this->isHttpException($e)) {
            if ($e->getStatusCode() == 404) {
                return response()->json([
                    'code' => 404,
                    'message' => 'Не найдено'
                ], 404);
            }
            if ($e->getStatusCode() == 500) {
                return response()->json([
                    'code' => 500,
                    'message' => 'Балять, апишка сломалась'
                ], 500);
            }
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
